services:
  - type: web
    name: your-app-name
    env: static
    buildCommand: npm run build
    staticPublishPath: /build
    routes:
      - type: rewrite
        source: "/*"
        destination:Â "/index.html"
